### ISSUE TITLE
关于训练时间

### ISSUE THREAD

**Issue by Capricorn231** [chenxin-dlut/TransT#66]
您好！论文中提到训练是在两张Nvidia Titan RTX上进行的，请问训练完1000个epoch大约需要多长时间呢？

**Comment by FreezerBreath** [comment]
貌似是两三天吧

**Comment by chenxin-dlut** [comment]
在两张卡上要8~9天。八张卡要2~3天。

**Comment by Capricorn231** [comment]
好的，非常感谢

**Comment by wanglibo0626** [comment]
![image](https://user-images.githubusercontent.com/38565240/131301836-bc55a4b0-76a8-48e7-81db-d1e94f20f0de.png)
作者您好，我在8张卡上跑了两天，目前仅跑完100个epoch,如果跑完1000个epoch，岂不是要20天左右？
还有请问是不是每修改一次代码，就要重新训练一次呢？

**Comment by chenxin-dlut** [comment]
> ![image](https://user-images.githubusercontent.com/38565240/131301836-bc55a4b0-76a8-48e7-81db-d1e94f20f0de.png)
> 作者您好，我在8张卡上跑了两天，目前仅跑完100个epoch,如果跑完1000个epoch，岂不是要20天左右？
> 还有请问是不是每修改一次代码，就要重新训练一次呢？

8卡建议改一下用ddp训练，一般三天是可以训完的。
如果要做对比实验，是应该改代码后重训的。

**Comment by wanglibo0626** [comment]
好的谢谢，如果是为了设计一个更好的模型，可以在之前的模型基础上接着训练嘛？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "chenxin-dlut/TransT"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月30日(星期一) 下午3:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [chenxin-dlut/TransT] 关于训练时间 (#66)





  

 作者您好，我在8张卡上跑了两天，目前仅跑完100个epoch,如果跑完1000个epoch，岂不是要20天左右？
 还有请问是不是每修改一次代码，就要重新训练一次呢？
  
8卡建议改一下用ddp训练，一般三天是可以训完的。
 如果要做对比实验，是应该改代码后重训的。
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by FreezerBreath** [comment]
> > ![image](https://user-images.githubusercontent.com/38565240/131301836-bc55a4b0-76a8-48e7-81db-d1e94f20f0de.png)
> > 作者您好，我在8张卡上跑了两天，目前仅跑完100个epoch,如果跑完1000个epoch，岂不是要20天左右？
> > 还有请问是不是每修改一次代码，就要重新训练一次呢？
> 
> 8卡建议改一下用ddp训练，一般三天是可以训完的。
> 如果要做对比实验，是应该改代码后重训的。

你好，我想问一下使用ddp训练，具体应该怎么做呢，有没有教程什么的可以模仿一下？
