### ISSUE TITLE
关于在VOT2020上的测试和验证

### ISSUE THREAD

**Issue by Soarkey** [chenxin-dlut/TransT#82]
请问作者是怎么在VOT2020数据集上测试和验证的呢，没有看到相关的代码，希望您可以指点一二，非常感谢

**Comment by xiaobai111111223** [comment]
同问
还有加入Alpha Refine和mask的代码会放开吗

**Comment by chenxin-dlut** [comment]
> 同问
> 还有加入Alpha Refine和mask的代码会放开吗
> 

seg分支的代码会开源，加alpha refine不如直接加seg分支的性能，所以就不放了，如果需要可以自己跟alpha refine合一下

**Comment by xiaobai111111223** [comment]
关于怎么结合可以说一下吗？可以借你和Alpha refine结合代码，学习一下嘛？最近在做以为这个代码为基础的改进，想启发一下思路

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年10月14日(周四) 上午8:07
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [chenxin-dlut/TransT] 关于在VOT2020上的测试和验证 (#82)




  
同问
 还有加入Alpha Refine和mask的代码会放开吗
  
seg分支的代码会开源，加alpha refine不如直接加seg分支的性能，所以就不放了，如果需要可以自己跟alpha refine合一下
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by xiaobai111111223** [comment]
非常感谢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年10月14日(周四) 上午8:07
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [chenxin-dlut/TransT] 关于在VOT2020上的测试和验证 (#82)




  
同问
 还有加入Alpha Refine和mask的代码会放开吗
  
seg分支的代码会开源，加alpha refine不如直接加seg分支的性能，所以就不放了，如果需要可以自己跟alpha refine合一下
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by chenxin-dlut** [comment]
> 关于怎么结合可以说一下吗？可以借你和Alpha refine结合代码，学习一下嘛？最近在做以为这个代码为基础的改进，想启发一下思路
> 
> ---原始邮件---
> 发件人: ***@***.***&gt;
> 发送时间: 2021年10月14日(周四) 上午8:07
> 收件人: ***@***.***&gt;;
> 抄送: ***@***.******@***.***&gt;;
> 主题: Re: [chenxin-dlut/TransT] 关于在VOT2020上的测试和验证 (#82)
> 
> 
> 
> 
>   
> 同问
>  还有加入Alpha Refine和mask的代码会放开吗
>   
> seg分支的代码会开源，加alpha refine不如直接加seg分支的性能，所以就不放了，如果需要可以自己跟alpha refine合一下
>  
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android.

就是把transt的输出直接送给alpha refine就可以了，也不需要重新训，很简单，可以参考alpha refine的代码，把里边的dimp的输出改成transt的输出即可
